const $=s=>document.querySelector(s),screens=[...document.querySelectorAll('.screen')];let level=0,q=0,total=0,pattern=null,startAt=0,taps=[],running=false,ctx,timers=[];
const banks={1:[{v:'♩ ♩ ♩ ♩',u:[0,2,4,6]}],2:[{v:'♫ ♩ ♫ ♩',u:[0,1,2,4,5,6]},{v:'♩ ♫ ♩ ♫',u:[0,2,3,4,6,7]}],3:[{v:'♬ ♩ 𝄽 ♫',u:[0,.5,1,1.5,2,6,7]},{v:'♫ 𝄽 ♬ ♩',u:[0,1,4,4.5,5,5.5,6]}],4:[{v:'♩. ♪ ♩ ♩',u:[0,1.5,2,4,6]},{v:'♩ ♩. ♪ ♩',u:[0,2,3.5,4,6]}]};
function go(id){screens.forEach(x=>x.classList.toggle('show',x.id===id))}document.querySelectorAll('[data-level]').forEach(c=>c.onclick=()=>{document.querySelectorAll('[data-level]').forEach(x=>x.classList.remove('selected'));c.classList.add('selected');level=+c.dataset.level;$('#start').disabled=false});
$('#start').onclick=start;$('#again').onclick=start;$('#back').onclick=()=>go('home');$('#homeBtn').onclick=()=>go('home');$('#next').onclick=next;$('#launch').onclick=launch;$('#tap').onpointerdown=tap;addEventListener('keydown',e=>{if(e.code==='Space'){e.preventDefault();tap()}});
function start(){q=0;total=0;go('game');next()}function next(){if(q>=6)return finish();q++;running=false;taps=[];pattern=banks[level][Math.floor(Math.random()*banks[level].length)];$('#rhythm').textContent=pattern.v;$('#count').textContent=`Rythme ${q}/6`;$('#score').textContent=`Précision ${Math.round(total/Math.max(1,q-1))}%`;$('#bar').style.width=`${(q-1)/6*100}%`;$('#tempo').textContent=`Tempo : ${level===1?72:level===2?84:level===3?76:88} ♩/min`;$('#feedback').textContent='';$('#feedback').className='feedback';$('#hits').innerHTML='';$('#next').classList.add('hidden');$('#launch').disabled=false;$('#tap').disabled=true;$('#cursor').className='cursor'}
function audio(){return ctx||(ctx=new (AudioContext||webkitAudioContext)())}function click(accent){let c=audio(),o=c.createOscillator(),g=c.createGain(),t=c.currentTime;o.frequency.value=accent?1200:750;g.gain.setValueAtTime(.16,t);g.gain.exponentialRampToValueAtTime(.0001,t+.06);o.connect(g).connect(c.destination);o.start(t);o.stop(t+.07)}
function launch(){timers.forEach(clearTimeout);timers=[];$('#launch').disabled=true;let bpm=level===1?72:level===2?84:level===3?76:88,unit=60000/bpm/2;for(let i=0;i<4;i++)timers.push(setTimeout(()=>click(i===0),i*unit*2));timers.push(setTimeout(()=>{running=true;taps=[];startAt=performance.now();$('#tap').disabled=false;$('#cursor').style.setProperty('--duration',`${unit*8}ms`);void $('#cursor').offsetWidth;$('#cursor').className='cursor run';timers.push(setTimeout(evaluate,unit*8+220))},unit*8))}
function tap(){if(!running)return;taps.push(performance.now()-startAt);$('#tap').classList.add('active');setTimeout(()=>$('#tap').classList.remove('active'),80);click(false)}
function evaluate(){running=false;$('#tap').disabled=true;let bpm=level===1?72:level===2?84:level===3?76:88,unit=60000/bpm/2,expected=pattern.u.map(x=>x*unit),available=[...taps],good=0,dots=[];expected.forEach(t=>{let best=-1,dist=Infinity;available.forEach((a,i)=>{if(Math.abs(a-t)<dist){dist=Math.abs(a-t);best=i}});let ok=best>=0&&dist<=unit*.42;if(ok){good++;available.splice(best,1)}dots.push(`<span class="hit ${ok?'good':'bad'}"></span>`)});let precision=Math.round(good/Math.max(expected.length,taps.length)*100);total+=precision;$('#hits').innerHTML=dots.join('');$('#feedback').textContent=precision>=85?`Excellent ! ${precision}% de précision 🎉`:precision>=60?`Bien ! ${precision}% — surveille les points rouges.`:`${precision}% — garde la pulsation et recommence tranquillement.`;$('#feedback').classList.add(precision>=60?'ok':'no');$('#bar').style.width=`${q/6*100}%`;$('#next').classList.remove('hidden')}
function finish(){go('results');let avg=Math.round(total/6);$('#result').textContent=`${avg}%`;$('#message').textContent=avg>=80?'Pulsation très stable, bravo !':'Continue : vise d’abord la régularité avant la vitesse.'}
