const $=s=>document.querySelector(s),screens=[...document.querySelectorAll('.screen')];
const chords={M:{name:'Majeur',intervals:[0,4,7],feeling:'lumineux et stable'},m:{name:'Mineur',intervals:[0,3,7],feeling:'plus sombre et doux'},dim:{name:'Diminué',intervals:[0,3,6],feeling:'tendu et instable'},aug:{name:'Augmenté',intervals:[0,4,8],feeling:'suspendu et mystérieux'},M7:{name:'Septième majeure',intervals:[0,4,7,11],feeling:'riche, douce et lumineuse'},'7':{name:'Septième de dominante',intervals:[0,4,7,10],feeling:'tendue, elle appelle une résolution'},m7:{name:'Septième mineure',intervals:[0,3,7,10],feeling:'souple, ronde et chaleureuse'},m7b5:{name:'Septième demi-diminuée',intervals:[0,3,6,10],feeling:'sombre et instable'},dim7:{name:'Septième diminuée',intervals:[0,3,6,9],feeling:'très tendue et symétrique'}};
const chordOrder=['M','m','dim','aug','M7','7','m7','m7b5','dim7'],sampleNames=['C','Csharp','D','Dsharp','E','F','Fsharp','G','Gsharp','A','Asharp','B'],letters=['Do','Ré','Mi','Fa','Sol','La','Si'],naturalPc=[0,2,4,5,7,9,11],naturalRoots=[60,62,64,65,67,69],inversionRoots=[48,50,52,53,55,57];
const STORAGE='accordsExpressProgressV2';
let selected=[],sequence=[],q=0,score=0,current=null,currentRoot=60,lastRoot=null,tutorialRoot=60,session={},baseTotal=10,total=10,gameMode='training',lives=3,combo=0,timeLeft=60,timerId=null;
function go(id){screens.forEach(x=>x.classList.toggle('show',x.id===id));if(id==='home')renderProgress()}
function loadStats(){try{return JSON.parse(localStorage.getItem(STORAGE))||{}}catch{return{}}}
function saveStats(stats){try{localStorage.setItem(STORAGE,JSON.stringify(stats))}catch{}}
function record(type,ok){const all=loadStats(),s=all[type]||{attempts:0,correct:0};s.attempts++;if(ok)s.correct++;s.last=Date.now();all[type]=s;saveStats(all);const x=session[type]||{attempts:0,correct:0};x.attempts++;if(ok)x.correct++;session[type]=x}
function pct(s){return s&&s.attempts?Math.round(s.correct/s.attempts*100):null}
function statsHtml(stats,types=chordOrder){return types.filter(id=>stats[id]?.attempts).map(id=>{const p=pct(stats[id]);return `<div class="stat"><strong>${chords[id].name}</strong><span>${p}%</span><small>${stats[id].correct}/${stats[id].attempts} réponses</small><i><b style="width:${p}%"></b></i></div>`}).join('')}
function renderProgress(){const stats=loadStats(),attempts=Object.values(stats).reduce((n,s)=>n+s.attempts,0),correct=Object.values(stats).reduce((n,s)=>n+s.correct,0);$('#progressSummary').textContent=attempts?`${attempts} questions · ${Math.round(correct/attempts*100)} % de réussite`:'Aucun exercice terminé pour le moment.';$('#homeStats').innerHTML=statsHtml(stats)}
document.querySelectorAll('#directChoice input').forEach(x=>x.onchange=updateSelection);
function updateSelection(){selected=[...document.querySelectorAll('#directChoice input:checked')].map(x=>x.value);const ok=selected.length>=2;$('#start').disabled=!ok;$('#selectionStatus').textContent=ok?`Niveau : ${selected.length<=3?selected.map(id=>chords[id].name).join(' · '):selected.length+' accords au choix'}`:'Choisis encore un accord pour commencer';$('#selectionStatus').classList.toggle('warning',!ok);document.querySelectorAll('[data-preset]').forEach(b=>{const preset=b.dataset.preset.split(',');b.classList.toggle('active',preset.length===selected.length&&preset.every(id=>selected.includes(id)))})}
updateSelection();renderProgress();
$('#resetStats').onclick=()=>{if(confirm('Effacer toute la progression mémorisée ?')){localStorage.removeItem(STORAGE);renderProgress()}};
document.querySelectorAll('[data-preset]').forEach(b=>b.onclick=()=>{const preset=b.dataset.preset.split(',');document.querySelectorAll('#directChoice input').forEach(x=>x.checked=preset.includes(x.value));updateSelection();document.querySelector('.start-zone').scrollIntoView({behavior:'smooth',block:'center'})});
document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{gameMode=b.dataset.mode;document.querySelectorAll('[data-mode]').forEach(x=>{x.classList.toggle('selected',x===b);x.querySelector('b').textContent=x===b?'Choisi':x.dataset.mode==='challenge'?'Jouer':'Choisir'});$('#start').textContent=gameMode==='challenge'?'Lancer le défi':'Commencer l’entraînement'});
$('#openTuto').onclick=()=>{tutorialRoot=60;renderTutorial();go('tuto')};$('#tutoBack').onclick=()=>go('home');$('#start').onclick=start;$('#back').onclick=()=>{stopTimer();go('home')};$('#homeBtn').onclick=()=>go('home');$('#again').onclick=start;$('#next').onclick=next;$('#play').onclick=playCurrent;
function sampleFile(midi){return `sounds/${sampleNames[midi%12]}${Math.floor(midi/12)-1}.mp3`}
function playNote(midi,delay=0){const start=()=>{const a=new Audio(sampleFile(midi));a.volume=.72;a.play().catch(()=>{})};delay?setTimeout(start,delay):start()}
function voicedIntervals(type,inversion=0){const ints=[...chords[type].intervals];for(let i=0;i<inversion;i++)ints[i]+=12;return ints.sort((a,b)=>a-b)}
function playChord(type,root=60,inversion=0){voicedIntervals(type,inversion).forEach(n=>playNote(root+n))}
function playCurrent(){playChord(current,currentRoot)}
function renderTutorial(){const group=(title,favorites,others)=>`<section class="tuto-family"><header><strong>${title}</strong></header><div class="favorite-chords">${favorites.map(id=>`<button data-tutorial="${id}" class="key-chord">★ ${chords[id].name}</button>`).join('')}</div><div class="other-chords">${others.map(id=>`<button data-tutorial="${id}">${chords[id].name}</button>`).join('')}</div></section>`;$('#tutoNav').innerHTML=group('Accords à 3 notes',['M','m'],['dim','aug'])+group('Accords à 4 notes',['7'],['M7','m7','m7b5','dim7']);document.querySelectorAll('[data-tutorial]').forEach(b=>b.onclick=()=>selectTutorial(b.dataset.tutorial));selectTutorial('M')}
function selectTutorial(id){
  document.querySelectorAll('[data-tutorial]').forEach(b=>b.classList.toggle('selected',b.dataset.tutorial===id));
  const c=chords[id],notes=spellChord(tutorialRoot,id),rootName=notes[0].label;
  const themes={M:['#4f819d','#edf4f7'],m:['#706f98','#f0f0f6'],dim:['#916e73','#f5f0f1'],aug:['#817394','#f3f0f5'],M7:['#5f8882','#eef5f3'],'7':['#4d789d','#edf3f8'],m7:['#687f94','#f0f3f6'],m7b5:['#737b84','#f2f3f4'],dim7:['#796d8b','#f2f0f4']},theme=themes[id];
  const observations={M:'Son clair et stable.',m:'Son plus sombre et doux.',dim:'Son tendu et instable.',aug:'Son ouvert, en suspens.',M7:'Son doux et lumineux.','7':'Son tendu, qui appelle une résolution.',m7:'Son souple et chaleureux.',m7b5:'Son sombre et instable.',dim7:'Son très tendu.'};
  const intervals=notes.slice(1).map((n,i)=>`<span><strong>${intervalLabel(c.intervals[i+1]).split(' (')[0]}</strong><small>${rootName} → ${n.label}</small></span>`).join('');
  const parts=constructionParts(id).map((part,i)=>`${i?'<b>+</b>':''}<span>${part}</span>`).join('');
  const rootOptions=naturalRoots.map(root=>`<option value="${root}" ${root===tutorialRoot?'selected':''}>${letters[naturalPc.indexOf(root%12)]}</option>`).join('');
  $('#tutoDetail').style.cssText=`--lesson:${theme[0]};--lesson-soft:${theme[1]}`;
  $('#tutoDetail').innerHTML=`<header class="lesson-title"><div class="lesson-identity"><span class="lesson-icon">♫</span><div><h3>${c.name}</h3><small>Exemple en ${rootName}</small></div></div><label>Note de départ <select id="tutorialRootChoice">${rootOptions}</select></label></header><div class="same-color">La note de départ change. La couleur de l’accord reste la même.</div><div class="lesson-main"><section class="listen-card"><h4>Écoute</h4><div id="tutoNotation" class="notation tutorial-notation"></div><strong class="tutorial-notes">${notes.map(n=>n.label).join(' – ')}</strong><div class="listening"><button id="tutoBlocked">▶ Notes ensemble</button><button id="tutoArp" class="arpeggio">♫ Notes séparées</button></div></section><section class="ear-card"><span>À l’oreille</span><h4>${observations[id]}</h4><p>Écoute les notes séparées, puis chante-les.</p></section></div><details class="theory-details"><summary>Comment l’accord est construit</summary><div class="theory-content"><div class="construction-parts">${parts}</div><div class="simple-intervals">${intervals}</div><p>Les intervalles restent les mêmes avec une autre note de départ.</p></div></details>`;
  renderNotation($('#tutoNotation'),notes);
  $('#tutorialRootChoice').onchange=e=>{tutorialRoot=Number(e.target.value);selectTutorial(id)};
  $('#tutoBlocked').onclick=()=>playChord(id,tutorialRoot);
  $('#tutoArp').onclick=()=>chords[id].intervals.forEach((n,i)=>playNote(tutorialRoot+n,i*230));
}
function constructionParts(id){return{M:['Tierce majeure','Quinte juste'],m:['Tierce mineure','Quinte juste'],dim:['Tierce mineure','Quinte diminuée'],aug:['Tierce majeure','Quinte augmentée'],M7:['Tierce majeure','Quinte juste','Septième majeure'],'7':['Tierce majeure','Quinte juste','Septième mineure'],m7:['Tierce mineure','Quinte juste','Septième mineure'],m7b5:['Tierce mineure','Quinte diminuée','Septième mineure'],dim7:['Tierce mineure','Quinte diminuée','Septième diminuée']}[id]}
function intervalLabel(n){return({3:'Tierce mineure (1,5 ton)',4:'Tierce majeure (2 tons)',6:'Quinte diminuée (3 tons)',7:'Quinte juste (3,5 tons)',8:'Quinte augmentée (4 tons)',9:'Septième diminuée (4,5 tons)',10:'Septième mineure (5 tons)',11:'Septième majeure (5,5 tons)'})[n]||`${n} demi-tons`}
function shuffle(a){a=[...a];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function validOrder(a){return !a.some((x,i)=>i>0&&x===a[i-1])}
function balancedSequence(count){const pool=Array.from({length:count},(_,i)=>selected[i%selected.length]);for(let n=0;n<800;n++){const a=shuffle(pool);if(validOrder(a))return a}return pool}
function adaptiveSequence(count){const stats=loadStats(),pool=[];selected.forEach(id=>{const p=pct(stats[id]),weight=p===null?3:Math.max(1,Math.ceil((105-p)/20));for(let i=0;i<weight;i++)pool.push(id)});const out=[];while(out.length<count){let options=[...pool];if(out.length>1&&out.at(-1)===out.at(-2))options=options.filter(id=>id!==out.at(-1));if(selected.length===2&&out.length>3&&out.slice(-3).every((x,i,a)=>i===0||x!==a[i-1]))options.push(out.at(-1),out.at(-1));out.push(options[Math.floor(Math.random()*options.length)])}return out}
function stopTimer(){if(timerId){clearInterval(timerId);timerId=null}}
function startTimer(){stopTimer();timeLeft=60;$('#timer').textContent='⏱ 60 s';timerId=setInterval(()=>{timeLeft--;$('#timer').textContent=`⏱ ${timeLeft} s`;$('#timer').classList.toggle('urgent',timeLeft<=10);if(timeLeft<=0){stopTimer();finish()}},1000)}
function start(){stopTimer();updateSelection();if(selected.length<2)return;q=0;score=0;lives=3;combo=0;lastRoot=null;session={};baseTotal=gameMode==='challenge'?15:10;total=baseTotal;sequence=balancedSequence(baseTotal);$('#gameLabel').textContent=gameMode==='challenge'?'Défi':'Entraînement';$('#challengeHud').classList.toggle('hidden',gameMode!=='challenge');go('game');next();if(gameMode==='challenge')startTimer()}
function next(){if(q>=sequence.length||(gameMode==='challenge'&&lives<=0))return finish();current=sequence[q];q++;const roots=naturalRoots.filter(root=>root!==lastRoot);currentRoot=roots[Math.floor(Math.random()*roots.length)];lastRoot=currentRoot;$('#count').textContent=`Question ${q}/${total}`;$('#score').textContent=gameMode==='challenge'?`${score} points`:`Score ${score}`;$('#lives').textContent='❤️'.repeat(lives)+'🖤'.repeat(3-lives);$('#combo').textContent=`Série ×${combo}`;$('#bar').style.width=`${(q-1)/total*100}%`;$('#feedback').textContent='';$('#feedback').className='feedback';$('#visualAnswer').classList.add('hidden');$('#next').classList.add('hidden');$('#answers').innerHTML='';selected.forEach(id=>{const b=document.createElement('button');b.textContent=chords[id].name;b.onclick=()=>answer(id,b);$('#answers').append(b)});playCurrent()}
function answer(id,b){[...$('#answers').children].forEach(x=>x.disabled=true);const ok=id===current;if(gameMode==='challenge'){if(ok){combo++;score+=100+(combo-1)*25}else{lives--;combo=0}}else if(ok)score++;record(current,ok);b.style.background=ok?'#4f9b67':'#cf6b68';if(!ok)[...$('#answers').children].find(x=>x.textContent===chords[current].name).classList.add('correct-answer');$('#feedback').textContent=ok?(gameMode==='challenge'?`Bien joué ! +${100+(combo-1)*25} points. 🎤 Chante les notes.`:'Bravo ! 🎤 Chante les notes affichées.'):(gameMode==='challenge'?`Une vie perdue. C’était ${chords[current].name}. 🎤 Chante les notes.`:`C’était un accord ${chords[current].name.toLowerCase()}. 🎤 Chante les notes affichées.`);$('#feedback').classList.add(ok?'ok':'no');$('#score').textContent=gameMode==='challenge'?`${score} points`:`Score ${score}`;$('#lives').textContent='❤️'.repeat(lives)+'🖤'.repeat(3-lives);$('#combo').textContent=`Série ×${combo}`;$('#bar').style.width=`${q/total*100}%`;showVisual();$('#next').textContent=q>=sequence.length||(gameMode==='challenge'&&lives<=0)?'Voir le résultat':'Question suivante';$('#next').classList.remove('hidden')}
function inversionLabel(i,size){if(!i)return'Position fondamentale';if(i===1)return'1er renversement';if(i===2)return'2e renversement';return size===4?'3e renversement':''}
function showVisual(){const notes=spellChord(currentRoot,current);$('#chordName').textContent=`${notes[0].label} ${chords[current].name}`;$('#staff').className='notation';renderNotation($('#staff'),notes);$('#noteNames').textContent=notes.map(n=>n.label).join(' – ');$('#visualAnswer').classList.remove('hidden')}
function spellChord(root,type,inversion=0){const rootLetter=naturalPc.indexOf(root%12),rootOct=Math.floor(root/12)-1,base=chords[type].intervals.map((interval,i)=>{const rawLetter=rootLetter+i*2,letterIndex=rawLetter%7,octave=rootOct+Math.floor(rawLetter/7),naturalMidi=(octave+1)*12+naturalPc[letterIndex],target=root+interval;let delta=target-naturalMidi;while(delta>6)delta-=12;while(delta<-6)delta+=12;const accidental=delta===1?'♯':delta===-1?'♭':delta===2?'𝄪':delta===-2?'𝄫':'';return{midi:target,letterIndex,octave,accidental,label:letters[letterIndex]+accidental}});for(let i=0;i<inversion;i++){base[i].midi+=12;base[i].octave++}return base.sort((a,b)=>a.midi-b.midi)}
function renderNotation(target,notes){
  target.innerHTML='';
  const {Renderer,Stave,StaveNote,Voice,Formatter,Accidental}=window.VexFlow;
  const tutorial=target.classList.contains('tutorial-notation'),game=target.id==='staff';
  const width=Math.max(280,Math.min(game?480:680,target.clientWidth||600));
  const height=tutorial?140:game?145:180;
  const renderer=new Renderer(target,Renderer.Backends.SVG);renderer.resize(width,height);
  const context=renderer.getContext(),stave=new Stave(12,18,width-24);
  stave.addClef('treble').setContext(context).draw();
  const eng=['c','d','e','f','g','a','b'],keys=notes.map(n=>`${eng[n.letterIndex]}/${n.octave}`);
  const note=new StaveNote({clef:'treble',keys,duration:'w'});
  notes.forEach((n,i)=>{if(n.accidental){const code=n.accidental==='♭'?'b':n.accidental==='♯'?'#':n.accidental==='𝄫'?'bb':'##';note.addModifier(new Accidental(code),i)}});
  const voice=new Voice({numBeats:4,beatValue:4}).addTickables([note]);
  new Formatter().joinVoices([voice]).format([voice],Math.max(150,width-150));
  note.getTickContext().setX(Math.max(90,width*.34));voice.draw(context,stave);
}
function finish(){stopTimer();go('results');const attempts=Object.values(session).reduce((n,s)=>n+s.attempts,0),correct=Object.values(session).reduce((n,s)=>n+s.correct,0),percent=attempts?Math.round(correct/attempts*100):0,grade=(percent/10).toLocaleString('fr-FR',{minimumFractionDigits:1,maximumFractionDigits:1}),stages=[{ids:['M','m'],label:'Majeur – Mineur'},{ids:['M','m','7'],label:'Majeur – Mineur – 7e de dominante'},{ids:['M','m','dim','aug'],label:'les quatre accords à 3 sons'},{ids:['M7','7','m7'],label:'les trois accords de 7e usuels'},{ids:['dim','m7b5','dim7'],label:'les couleurs diminuées'}],stageIndex=stages.findIndex(s=>s.ids.length===selected.length&&s.ids.every(id=>selected.includes(id)));$('#sessionStats').innerHTML=statsHtml(session,selected);$('#grade').textContent=`${grade} / 10`;if(gameMode==='challenge'){$('#result').textContent=`${score} pts`;$('#message').textContent=timeLeft<=0?'Temps écoulé.':lives>0?'Défi terminé.':'Plus de vies.';$('#recommendation').innerHTML=`<strong>${correct}/${attempts}</strong> bonnes réponses · ${percent}&nbsp;%.`;return}$('#result').textContent=`${percent} %`;$('#message').textContent=percent>=80?'Très bien ! Tu peux passer à l’étape suivante.':'Refais une série avec les mêmes accords.';if(stageIndex>=0&&percent<80){$('#recommendation').innerHTML=`<strong>À refaire :</strong> ${stages[stageIndex].label}.`}else if(stageIndex>=0&&stages[stageIndex+1]){$('#recommendation').innerHTML=`<strong>Ensuite :</strong> ${stages[stageIndex+1].label}.`}else{$('#recommendation').innerHTML=percent<80?'Garde les mêmes accords pour la prochaine série.':'Choisis une nouvelle étape.'}}
