const $=s=>document.querySelector(s),screens=[...document.querySelectorAll('.screen')];let level=0,q=0,score=0,target=[],entry=[],ctx,timers=[];
const items={q:{name:'♩ Noire',units:2,sound:[0]},e:{name:'♫ 2 croches',units:2,sound:[0,1]},h:{name:'𝅗𝅥 Blanche',units:4,sound:[0]},r:{name:'𝄽 Soupir',units:2,sound:[]},s:{name:'♬ 4 doubles',units:2,sound:[0,.5,1,1.5]},d:{name:'♩. Croche',units:2,sound:[0,1.5]}};
const patterns={1:[['q','q','q','q'],['e','q','e','q'],['q','e','q','e']],2:[['h','q','q'],['q','r','e','q'],['r','q','h']],3:[['s','q','e','q'],['e','s','q','q'],['q','s','e','q']],4:[['d','d','q','q'],['d','q','d','q'],['q','d','d','q']]};
function go(id){screens.forEach(x=>x.classList.toggle('show',x.id===id))}document.querySelectorAll('[data-level]').forEach(c=>c.onclick=()=>{document.querySelectorAll('[data-level]').forEach(x=>x.classList.remove('selected'));c.classList.add('selected');level=+c.dataset.level;$('#start').disabled=false});
$('#start').onclick=start;$('#again').onclick=start;$('#homeBtn').onclick=()=>go('home');$('#back').onclick=()=>go('home');$('#next').onclick=next;$('#undo').onclick=()=>{entry.pop();render()};$('#check').onclick=check;$('#listen').onclick=play;
function start(){q=0;score=0;go('game');next()}function next(){if(q>=8)return finish();q++;entry=[];target=patterns[level][Math.floor(Math.random()*patterns[level].length)];$('#count').textContent=`Question ${q}/8`;$('#score').textContent=`Score ${score}`;$('#bar').style.width=`${(q-1)*12.5}%`;$('#feedback').textContent='';$('#feedback').className='feedback';$('#next').classList.add('hidden');$('#check').disabled=false;buildPalette();render();play()}
function buildPalette(){const allowed=level===1?['q','e']:level===2?['q','e','h','r']:level===3?['q','e','s']:['q','e','d'];$('#palette').innerHTML='';allowed.forEach(k=>{let b=document.createElement('button');b.textContent=items[k].name;b.onclick=()=>add(k);$('#palette').append(b)})}
function used(){return entry.reduce((n,k)=>n+items[k].units,0)}function add(k){if(used()+items[k].units<=8){entry.push(k);render()}}function render(){let html='',u=0;entry.forEach(k=>{const span=items[k].units;html+=`<div class="slot filled" style="grid-column:span ${span}">${items[k].name.split(' ')[0]}</div>`;u+=span});while(u<8){html+='<div class="slot"></div>';u++}$('#measure').innerHTML=html}
function audio(){return ctx||(ctx=new (window.AudioContext||window.webkitAudioContext)())}function click(accent=false){const c=audio(),o=c.createOscillator(),g=c.createGain();o.frequency.value=accent?1200:760;g.gain.value=.0001;o.connect(g).connect(c.destination);let t=c.currentTime;g.gain.setValueAtTime(accent?.2:.12,t);g.gain.exponentialRampToValueAtTime(.0001,t+.07);o.start(t);o.stop(t+.08)}
function play(){timers.forEach(clearTimeout);timers=[];let unit=0;target.forEach(k=>{items[k].sound.forEach(off=>timers.push(setTimeout(click,(unit+off)*250)));unit+=items[k].units});for(let i=0;i<4;i++)timers.push(setTimeout(()=>{$('#beat').classList.add('on');click(i===0);setTimeout(()=>$('#beat').classList.remove('on'),90)},i*500))}
function check(){if(used()<8){$('#feedback').textContent='Complète toute la mesure avant de vérifier.';return}const ok=entry.join()==target.join();if(ok)score++;$('#feedback').textContent=ok?'Bravo ! Le rythme est exact 🎉':`Presque ! Réponse : ${target.map(k=>items[k].name).join(' | ')}`;$('#feedback').classList.add(ok?'ok':'no');$('#score').textContent=`Score ${score}`;$('#bar').style.width=`${q*12.5}%`;$('#check').disabled=true;$('#next').classList.remove('hidden')}
function finish(){go('results');$('#result').textContent=`${score}/8`;$('#message').textContent=score>=6?'Excellent sens du rythme !':'Bien joué : réécoute les pulsations et recommence.'}
