const $=s=>document.querySelector(s),screens=[...document.querySelectorAll('.screen')];
const sampleNames=['C','Csharp','D','Dsharp','E','F','Fsharp','G','Gsharp','A','Asharp','B'];
const tonalities={
  C:{name:'Do majeur',signature:'C',scale:[60,62,64,65,67,69,71,72],labels:['Do grave','Ré','Mi','Fa','Sol','La','Si','Do aigu']},
  F:{name:'Fa majeur',signature:'F',scale:[65,67,69,70,72,74,76,77],labels:['Fa grave','Sol','La','Si♭','Do','Ré','Mi','Fa aigu']},
  G:{name:'Sol majeur',signature:'G',scale:[67,69,71,72,74,76,78,79],labels:['Sol grave','La','Si','Do','Ré','Mi','Fa♯','Sol aigu']}
};
const banks={
  1:[[0,1,2,1,0],[2,3,4,3,2],[4,5,6,5,4],[7,6,5,6,7],[1,2,3,4,3,2],[5,4,3,2,3,4],[0,1,2,3,2,1,0],[7,6,5,4,5,6,7]],
  2:[[0,1,2,1,0,7,6,7],[7,6,5,6,7,0,1,0],[0,7,6,5,6,7,0],[7,0,1,2,1,0,7],[0,1,0,7,6,5,6,7],[7,6,7,0,1,2,1,0],[0,7,6,7,0,1,2,0],[7,0,1,0,7,6,5,7]],
  3:[[0,2,1,3,2,0],[2,4,3,5,4,2],[0,1,3,2,1,0],[5,3,4,2,3,5],[0,2,4,3,2,0],[7,5,6,4,5,7],[1,3,2,4,3,1],[6,4,5,3,4,6]],
  4:[[0,3,2,4,3,1,0],[0,4,3,5,4,2,0],[5,1,2,4,3,1,0],[0,2,5,4,3,1,0],[7,3,4,2,1,3,0],[2,6,5,3,4,2,0],[0,3,5,4,2,1,0],[7,4,2,3,1,2,0]],
  5:[[0,1,2,1,0],[0,2,1,3,2,0],[0,3,2,4,3,1,0],[0,4,3,5,4,2,0],[0,5,4,2,3,1,0],[0,6,5,3,4,2,0],[0,7,6,4,5,2,0],[0,2,4,7,6,4,2,0]]
};
let level=0,q=0,score=0,target=[],entry=[],currentRhythm=[],melodyQueue=[],selectedKey='C',currentKey=tonalities.C,playTimers=[],activeAudios=[],activeSources=[];
const audioCache=new Map();
const AudioCtx=window.AudioContext||window.webkitAudioContext,audioContext=AudioCtx?new AudioCtx():null,bufferCache=new Map();
function go(id){screens.forEach(x=>x.classList.toggle('show',x.id===id))}
document.querySelectorAll('[data-level]').forEach(c=>c.onclick=()=>{document.querySelectorAll('[data-level]').forEach(x=>x.classList.remove('selected'));c.classList.add('selected');level=+c.dataset.level;$('#start').disabled=false});
document.querySelectorAll('[data-key]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-key]').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');selectedKey=b.dataset.key});
$('#start').onclick=start;$('#again').onclick=start;$('#back').onclick=()=>go('home');$('#homeBtn').onclick=()=>go('home');$('#next').onclick=next;$('#undo').onclick=()=>{if(entry.length>1)entry.pop();renderEntry()};$('#check').onclick=check;$('#listen').onclick=play;$('#listenAnswer').onclick=playAnswer;
function start(){q=0;score=0;melodyQueue=buildMelodyQueue();go('game');next()}
function melodyVariants(patterns){const variants=[];patterns.forEach(pattern=>{const inverted=pattern.map(d=>7-d),candidates=[pattern,[...pattern].reverse(),inverted,[...inverted].reverse()];candidates.forEach(candidate=>{const min=Math.min(...candidate),max=Math.max(...candidate),shifts=[0,-min,7-max];shifts.forEach(shift=>variants.push(candidate.map(d=>d+shift)))})});const unique=[...new Map(variants.filter(notes=>notes.every(d=>d>=0&&d<=7)).map(notes=>[notes.join(','),notes])).values()];return shuffle(unique)}
function buildMelodyQueue(){const rhythmMotifs=[[.68,.58,.82,.62],[.58,.72,.58,.86],[.76,.54,.64,.72],[.62,.62,.78,.56],[.72,.64,.56,.82]],rhythmFor=(len,index)=>{const pulse=rhythmMotifs[index%rhythmMotifs.length];return Array.from({length:len},(_,i)=>i===len-1?1.35:pulse[i%pulse.length])},patterns=melodyVariants(banks[level]).slice(0,8);return patterns.map((degrees,i)=>{const keyId=selectedKey==='mixed'?shuffle(['C','F','G'])[0]:selectedKey,key=tonalities[keyId];return{key,notes:degrees.map(d=>key.scale[d]),rhythm:rhythmFor(degrees.length,i)}})}
function next(){if(q>=8)return finish();const item=melodyQueue[q];q++;entry=[];currentKey=item.key;target=item.notes;currentRhythm=item.rhythm;entry=[target[0]];$('#count').textContent=`Mélodie ${q}/8`;$('#keyBadge').textContent=currentKey.name;$('#score').textContent=`Score ${score}`;$('#bar').style.width=`${(q-1)*12.5}%`;$('#feedback').textContent='';$('#feedback').className='feedback';$('#next').classList.add('hidden');$('#check').disabled=false;renderStaff(false);buildKeyboard();renderEntry();play()}
function shuffle(items){const copy=[...items];for(let i=copy.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[copy[i],copy[j]]=[copy[j],copy[i]]}return copy}
function sampleFile(midi){return `sounds/${sampleNames[midi%12]}${Math.floor(midi/12)-1}.mp3`}
function stopPlayback(){playTimers.forEach(clearTimeout);playTimers=[];activeSources.forEach(source=>{try{source.stop()}catch(_){}});activeSources=[];activeAudios.forEach(a=>{a.pause();a.currentTime=0});activeAudios=[]}
function preloadSamples(){const notes=new Set(Object.values(tonalities).flatMap(key=>key.scale));notes.forEach(midi=>{const audio=new Audio(sampleFile(midi));audio.preload='auto';audio.load();audioCache.set(midi,audio)})}
function makeAudio(midi,volume=.58){const source=audioCache.get(midi);const audio=source?source.cloneNode(true):new Audio(sampleFile(midi));audio.preload='auto';audio.volume=volume;audio.addEventListener('ended',()=>{activeAudios=activeAudios.filter(item=>item!==audio)},{once:true});return audio}
function loadBuffer(midi){if(!audioContext)return Promise.reject(new Error('Web Audio indisponible'));if(bufferCache.has(midi))return bufferCache.get(midi);const promise=new Promise((resolve,reject)=>{const request=new XMLHttpRequest();request.open('GET',sampleFile(midi),true);request.responseType='arraybuffer';request.onload=()=>request.status===0||request.status<400?audioContext.decodeAudioData(request.response).then(resolve,reject):reject(new Error('Son introuvable'));request.onerror=reject;request.send()});bufferCache.set(midi,promise);return promise}
preloadSamples();
function play(){playSequence(target,currentRhythm)}function playAnswer(){playSequence(entry,currentRhythm.slice(0,entry.length))}
async function playSequence(notes,rhythm){stopPlayback();if(audioContext){try{await audioContext.resume();const buffers=await Promise.all(notes.map(loadBuffer));stopPlayback();const start=audioContext.currentTime+.08;let elapsed=0;buffers.forEach((buffer,i)=>{const source=audioContext.createBufferSource(),gain=audioContext.createGain();source.buffer=buffer;gain.gain.value=i===buffers.length-1?.62:.55;source.connect(gain).connect(audioContext.destination);source.start(start+elapsed);activeSources.push(source);source.onended=()=>{activeSources=activeSources.filter(item=>item!==source)};elapsed+=rhythm[i]||.68});return}catch(_){}}let elapsed=0;notes.forEach((midi,i)=>{playTimers.push(setTimeout(()=>{const audio=makeAudio(midi,i===notes.length-1?.62:.56);activeAudios.push(audio);audio.play().catch(()=>{})},Math.round(elapsed*1000)));elapsed+=rhythm[i]||.68})}
function label(midi){const i=currentKey.scale.indexOf(midi);return i>=0?currentKey.labels[i]:'?'}
function buildKeyboard(){$('#keyboard').innerHTML='';currentKey.scale.forEach((midi,i)=>{const b=document.createElement('button');b.textContent=currentKey.labels[i];b.onclick=()=>{if(entry.length<target.length){entry.push(midi);previewNote(midi);renderEntry()}};$('#keyboard').append(b)})}
function renderEntry(){const remaining=target.length-entry.length;$('#sequence').innerHTML=entry.map((n,i)=>`<span class="chip">${label(n)}${i===0?' ✓':''}</span>`).join('');$('#remaining').textContent=remaining?`Encore ${remaining} note${remaining>1?'s':''} à placer`:'Réponse complète ✓';$('#remaining').classList.toggle('complete',remaining===0);$('#check').disabled=remaining>0;$('#listenAnswer').disabled=entry.length===0;renderResponseStaff()}
async function previewNote(midi){stopPlayback();if(audioContext){try{await audioContext.resume();const buffer=await loadBuffer(midi);stopPlayback();const source=audioContext.createBufferSource(),gain=audioContext.createGain();source.buffer=buffer;gain.gain.value=.62;source.connect(gain).connect(audioContext.destination);source.start(audioContext.currentTime+.03);activeSources=[source];source.onended=()=>{activeSources=activeSources.filter(item=>item!==source)};return}catch(_){}}const audio=makeAudio(midi,.62);activeAudios=[audio];audio.play().catch(()=>{})}
function renderResponseStaff(){const VF=window.VexFlow,{Renderer,Stave,StaveNote,TickContext}=VF,host=$('#responseStaff');host.replaceChildren();const renderer=new Renderer(host,Renderer.Backends.SVG);renderer.resize(680,128);const context=renderer.getContext(),stave=new Stave(16,5,648);stave.addClef('treble');if(currentKey.signature!=='C')stave.addKeySignature(currentKey.signature);stave.setContext(context).draw();const total=target.length,startX=currentKey.signature==='C'?20:34,noteEndX=520,questionEndX=600,gap=total>1?(noteEndX-startX)/(total-1):0,keyNames=['c','c#','d','eb','e','f','f#','g','ab','a','bb','b'];entry.forEach((midi,i)=>{const octave=Math.floor(midi/12)-1,pc=midi%12,note=new StaveNote({clef:'treble',keys:[`${keyNames[pc]}/${octave}`],duration:'q',autoStem:true});new TickContext().addTickable(note).preFormat().setX(startX+i*gap);note.setContext(context).setStave(stave).draw();const noteGroup=note.getSVGElement?.();if(noteGroup){noteGroup.classList.add('answer-note');noteGroup.dataset.answerIndex=String(i);noteGroup.dataset.noteX=String(note.getAbsoluteX());noteGroup.dataset.noteY=String(note.getYs()[0])}});const svg=host.querySelector('svg');svg.setAttribute('viewBox','0 0 680 128');svg.removeAttribute('width');svg.removeAttribute('height');const labelNs='http://www.w3.org/2000/svg';entry.forEach((midi,i)=>{const noteLabel=document.createElementNS(labelNs,'text'),labelX=startX+i*gap+68;noteLabel.setAttribute('x',labelX);noteLabel.setAttribute('y','120');noteLabel.setAttribute('text-anchor','middle');noteLabel.setAttribute('font-size','11');noteLabel.setAttribute('font-weight','800');noteLabel.setAttribute('fill',i===0?'#1565c0':'#2c3e50');noteLabel.setAttribute('class','staff-note-label');noteLabel.textContent=label(midi)+(i===0?' ✓':'');svg.append(noteLabel)});const ns='http://www.w3.org/2000/svg';for(let i=entry.length;i<total;i++){const questionStart=startX+160,questionGap=total>2?(questionEndX-questionStart)/(total-2):0,x=questionStart+(i-1)*questionGap,g=document.createElementNS(ns,'g'),circle=document.createElementNS(ns,'circle'),text=document.createElementNS(ns,'text');circle.setAttribute('cx',x);circle.setAttribute('cy','64');circle.setAttribute('r','14');circle.setAttribute('fill','#f5f7fa');circle.setAttribute('stroke','#9fb7cc');circle.setAttribute('stroke-width','2');circle.setAttribute('stroke-dasharray','4 3');text.setAttribute('x',x);text.setAttribute('y','70');text.setAttribute('text-anchor','middle');text.setAttribute('font-size','15');text.setAttribute('font-weight','800');text.setAttribute('fill','#607d8b');text.setAttribute('class','answer-slot-number');text.textContent=String(i+1);g.append(circle,text);svg.append(g)}}
function renderStaff(reveal){const VF=window.VexFlow,{Renderer,Stave,StaveNote,TickContext}=VF,host=$('#staff');host.replaceChildren();const renderer=new Renderer(host,Renderer.Backends.SVG);renderer.resize(720,142);const context=renderer.getContext(),stave=new Stave(18,16,684);stave.addClef('treble');if(currentKey.signature!=='C')stave.addKeySignature(currentKey.signature);stave.setContext(context).draw();const count=target.length,startX=currentKey.signature==='C'?20:34,noteEndX=535,questionEndX=620,gap=count>1?(noteEndX-startX)/(count-1):0,keyNames=['c','c#','d','eb','e','f','f#','g','ab','a','bb','b'];target.forEach((midi,i)=>{if(i&&!reveal)return;const octave=Math.floor(midi/12)-1,pc=midi%12,note=new StaveNote({clef:'treble',keys:[`${keyNames[pc]}/${octave}`],duration:'q',autoStem:true});note.noteHeads.forEach(h=>h.setFontSize(h.fontSizeInPoints*1.28));new TickContext().addTickable(note).preFormat().setX(startX+i*gap);note.setContext(context).setStave(stave).draw()});const svg=host.querySelector('svg');svg.setAttribute('viewBox','0 0 720 142');svg.removeAttribute('width');svg.removeAttribute('height');if(!reveal){const ns='http://www.w3.org/2000/svg';target.forEach((_,i)=>{if(i===0)return;const questionStart=startX+160,questionGap=count>2?(questionEndX-questionStart)/(count-2):0,x=questionStart+(i-1)*questionGap,g=document.createElementNS(ns,'g'),circle=document.createElementNS(ns,'circle'),text=document.createElementNS(ns,'text');circle.setAttribute('cx',x);circle.setAttribute('cy','76');circle.setAttribute('r','18');circle.setAttribute('fill','#e3f2fd');circle.setAttribute('stroke','#2196f3');circle.setAttribute('stroke-width','2.5');text.setAttribute('x',x);text.setAttribute('y','83');text.setAttribute('text-anchor','middle');text.setAttribute('font-size','23');text.setAttribute('font-weight','800');text.setAttribute('fill','#1565c0');text.textContent='?';g.append(circle,text);svg.append(g)})}}
function check(){if(entry.length<target.length){$('#feedback').textContent='Place toutes les notes avant de vérifier.';return}const errors=entry.map((n,i)=>n===target[i]?null:i).filter(i=>i!==null),ok=errors.length===0,chips=$('#sequence').querySelectorAll('.chip');chips.forEach((chip,i)=>chip.classList.add(errors.includes(i)?'answer-wrong':'answer-correct'));$('#responseStaff').querySelectorAll('.answer-note').forEach(noteGroup=>{const i=Number(noteGroup.dataset.answerIndex),wrong=errors.includes(i);noteGroup.querySelectorAll('*').forEach(shape=>{const color=wrong?'#d32f2f':'#25823a';shape.setAttribute('fill',color);shape.setAttribute('stroke',color);shape.style.fill=color;shape.style.stroke=color});if(wrong){const ns='http://www.w3.org/2000/svg',x=Number(noteGroup.dataset.noteX),y=Number(noteGroup.dataset.noteY),ring=document.createElementNS(ns,'circle'),cross=document.createElementNS(ns,'text');ring.setAttribute('cx',x);ring.setAttribute('cy',y);ring.setAttribute('r','17');ring.setAttribute('fill','#ffebee');ring.setAttribute('fill-opacity','.72');ring.setAttribute('stroke','#d32f2f');ring.setAttribute('stroke-width','4');cross.setAttribute('x',x);cross.setAttribute('y',y-22);cross.setAttribute('text-anchor','middle');cross.setAttribute('font-size','21');cross.setAttribute('font-weight','900');cross.setAttribute('fill','#d32f2f');cross.textContent='✕';noteGroup.parentNode.insertBefore(ring,noteGroup);noteGroup.parentNode.append(cross)}});$('#responseStaff').querySelectorAll('.staff-note-label').forEach((noteLabel,i)=>{const wrong=errors.includes(i);noteLabel.setAttribute('fill',wrong?'#d32f2f':'#25823a');noteLabel.setAttribute('font-size',wrong?'14':'11');noteLabel.setAttribute('font-weight','900');if(wrong&&!noteLabel.textContent.endsWith(' ✗'))noteLabel.textContent+=' ✗'});if(ok){score++;$('#feedback').textContent='Bravo ! La mélodie est exacte 🎉';$('#feedback').classList.add('ok')}else{$('#feedback').innerHTML=`<strong>À corriger :</strong><br>${errors.map(i=>`Note ${i+1} : tu as choisi <strong>${label(entry[i])}</strong>, il fallait <strong>${label(target[i])}</strong>.`).join('<br>')}`;$('#feedback').classList.add('no','error-detail')}renderStaff(true);$('#score').textContent=`Score ${score}`;$('#bar').style.width=`${q*12.5}%`;$('#check').disabled=true;$('#next').classList.remove('hidden')}
function finish(){stopPlayback();go('results');$('#result').textContent=`${score}/8`;$('#message').textContent=score>=6?'Très belle oreille mélodique !':'Bien joué : chante intérieurement chaque mouvement avant de répondre.'}
